# Generated by Django 5.1 on 2024-10-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cadastro_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.TextField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='usuario',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
