# Generated by Django 5.1 on 2024-10-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cadastro_cpf_alter_cadastro_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='id',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='id_usuario',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
