# Generated by Django 5.1 on 2024-10-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cadastro_id_cadastro_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(max_length=100),
        ),
    ]
