# Generated by Django 5.1 on 2024-10-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cadastro_id_usuario_remove_cadastro_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
