# Generated by Django 5.1 on 2024-10-27 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cadastro_is_active_cadastro_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='last_login',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargo'),
        ),
    ]
