# Generated by Django 5.1 on 2024-10-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cadastro_cargo_agendamento_delete_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
