# Generated by Django 5.1 on 2024-11-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cadastro_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='last_login',
        ),
    ]
