# Generated by Django 5.1 on 2024-11-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_agendamento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Remarcado', 'Remarcado'), ('Recusado', 'Recusado')], default='Pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='convenio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.CharField(max_length=255),
        ),
    ]
