# Generated by Django 5.1 on 2024-11-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_agendamento_status_alter_agendamento_convenio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='cargo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('recepcao', 'Recepção'), ('admin', 'Administrador')], default='cliente', max_length=10),
        ),
    ]
