# Generated by Django 5.1.1 on 2024-11-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_cadastro_cargo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cadastro",
            name="cargo",
        ),
    ]
