"""
Django settings for sgo project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-mn0la^q*2%10n%7ajk#-1i68yo2$#2fj9ruggnz8^evfrb&2gi"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sgo.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Motor de template do Django.
        'DIRS': [BASE_DIR / 'templates'],  # Diretório de templates personalizados.
        'APP_DIRS': True,  # Django procura templates dentro de cada aplicação.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # Adiciona variáveis de depuração.
                'django.template.context_processors.request',  # Adiciona 'request' ao contexto dos templates.
                'django.contrib.auth.context_processors.auth',  # Adiciona variáveis relacionadas à autenticação.
                'django.contrib.messages.context_processors.messages',  # Adiciona mensagens ao contexto dos templates.
            ],
        },
    },
]

WSGI_APPLICATION = "sgo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Internacionalização.
LANGUAGE_CODE = 'pt-br'  # Código da língua.
TIME_ZONE = 'America/Sao_Paulo'  # Fuso horário.
USE_I18N = True  # Habilita internacionalização.
USE_TZ = True  # Habilita suporte a fuso horário.

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "core" / "static"]

# Configurações de autenticação e redirecionamento.
LOGIN_REDIRECT_URL = '/home/'  # URL para redirecionar após login.
LOGIN_URL = 'login'  # URL para página de login.
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'afonsecacaua@gmail.com'
EMAIL_HOST_PASSWORD = 'megb eqch inhb hksq'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
